### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by nouryehia** [amtjitro/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
   - not counting keystrokes
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
- I recommend organizing the images in your repo in an image folder and in subfolders for each lab. There will be a lot of images in the quarter and this helps keep a clean repo :)
--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by amtjitro** [comment]
Hi! By "counting keystrokes" do you mean count the number of commands we'd have to write out? For example, I fixed mine to say that I could run a file remotely through one keystroke/command instead of 4 (ssh, javac, java, then exit). Or does keystroke imply something else?

Thank you!

**Comment by nouryehia** [comment]
Hi, sorry for the late reply. keystrokes

**Comment by nouryehia** [comment]
Hi sorry for the late reply. Keystrokes refer to every key pressed on the keyboard and every click of the mouse. Seems like you had it right in the report!
